batch_size: 1024
train_batch_size: ${dataset.batch_size}
eval_batch_size: ${dataset.batch_size}

train_dataset:
  _target_: composer.datasets.build_streaming_cifar10_dataloader
  remote: s3://mosaicml-internal-dataset-cifar10/mds/1/
  local: /tmp/mds-cache/mds-cifar10/
  version: 1
  split: train
  shuffle: true
  drop_last: true
  prefetch_factor: 2
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  timeout: 0

eval_dataset:
  _target_: composer.datasets.build_streaming_cifar10_dataloader
  remote: s3://mosaicml-internal-dataset-cifar10/mds/1/
  local: /tmp/mds-cache/mds-cifar10/
  version: 1
  split: val
  shuffle: false
  drop_last: false
  prefetch_factor: 2
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  timeout: 0
