wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1660161375.591282
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      - 66
      2:
      - 1
      - 41
      - 50
      - 55
      - 66
      3:
      - 13
      - 23
      4: 3.9.13
      5: 0.13.1
      8:
      - 5
